name: Update Stage Branch

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-stage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Update stage branch
        run: |
          # Fetch all branches
          git fetch origin
          
          # Checkout stage branch
          git checkout stage
          git pull origin stage
          
          # Reset stage to match the PR branch
          git reset --hard origin/${{ github.head_ref }}
          
          # Force push to stage
          git push origin stage --force
          
          echo "✅ Stage branch has been updated to match ${{ github.head_ref }}"
      
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const timestamp = new Date().toISOString();
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Stage updated from \`${{ github.head_ref }}\` at ${timestamp} • [Re-run](${runUrl})`
            })